{{- if .Values.dra.enabled }}
{{- range .Values.dra.claims }}
---
apiVersion: resource.k8s.io/v1
kind: ResourceClaim
metadata:
  name: {{ include "llm-d-inference-sim.fullname" $ }}-{{ .name }}
spec:
  devices:
    requests:
    - name: {{ .name }}
      exactly:
        deviceClassName: {{ .deviceClassName }}
        {{- with .requests }}
        capacity:
          requests:
            {{- toYaml . | nindent 12 }}
        {{- end }}
{{- end }}
{{- end }}
