{{- if eq .Values.preset "dra" }}
apiVersion: resource.k8s.io/v1
kind: ResourceClaimTemplate
metadata:
  name: {{ .Values.dra.resourceClaimTemplate.name }}
  labels:
    {{- include "llm-d-inference-sim-demo.labels" . | nindent 4 }}
spec:
  spec:
    devices:
      requests:
      - name: gpu
        exactly:
          deviceClassName: {{ .Values.dra.resourceClaimTemplate.deviceClassName }}
          capacity:
            requests:
              memory: {{ .Values.dra.resourceClaimTemplate.memory | quote }}
              compute: {{ .Values.dra.resourceClaimTemplate.compute | quote }}
{{- end }}
